spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
      schema_update:
        unique_constraint_strategy: RECREATE_QUIETLY
  datasource:
    url: jdbc:mysql://localhost:3306/angular_app
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#jwt:
#  secret: AngularAndJavaAppSecretKeyAndJavaAndAngularAppSecretKeyAngularAndJavaAppSecretKey
#  expiration: 60000
#  jwtRefreshExpirationMs: 120000